### ISSUE TITLE
Device SID

### ISSUE THREAD

**Issue by spanchenko** [theo-69/homebridge-mi-aqara-platform#3]
Dear theo-69,

How to get device SID in order to build DefaultValue node.
In your example you provide
 {
            "platform": "MiAqaraPlatform",
            "gateways": {
                "34ce008d44b2": "F75FD945D6264B8F"
            },
            "defaultValue": {
                "34ce008d44b2": {
                    "Gateway_Lightbulb": {
                        "name": "Свет шлюза",
                        "serviceType": "Lightbulb"
                    },
                    "Gateway_LightSensor": {
                        "name": "Свет"
                    },
                    "Gateway_Switch_JoinPermission": {
                        "name": "Разрешение на подключение",
                        "disable": true
                    }
                },
                "158d000122b22": {
                    "PlugBase_Outlet_b442": {
                        "name": "Розетка"
                    }
                },
                "158d0001ddb013": {
                    "TemperatureAndHumiditySensor_TemperatureSensor": {
                        "name": "Температура"
                    },
                    "TemperatureAndHumiditySensor_HumiditySensor": {
                        "name": "Влажность"
                    }
                }
            }
        },

How did you get 34ce008d44b2, 158d000122b22, etc values?

Thanks.

**Comment by xrust83** [comment]
Последнее обновление проєкта 3 года назад, но параллельные ветки тоже уже не актуальны давно. Покупай zigbee stick, переходи на zigbee2mqtt.io и homebridge-z2m, а свой mi gateway 2 выставь на продажу :-(

Что касается sid то в старих версиях mi home можно было войти в режим разработчика. нужно было в нажать на пустое место, появлялось дополнительное меню. Уже не актуально тоже. 

https://stupidhouse.info/node/3/

**Comment by spanchenko** [comment]
Thanks
